#!/usr/bin/env tsx
import fs from 'fs';
import path from 'path';
import { pathToFileURL } from 'url';
import type { IssueLog, CompareReport } from '../schemas/issue.schema';
import type { DataRoomSummary } from '../schemas/spreadsheet.schema';
import { buildCompareReport } from '../lib/compare-engine';
import { escapeHtml } from '../lib/output-safety';
import { listRegularFiles, resolveInside, resolveRegularFileInside } from '../lib/path-safety';

const CWD = process.cwd();
const COMPARE_DIR = path.join(CWD, 'reports', 'compare');
const DISCLAIMER =
  'Synth is not legal advice or financial advice. It is a document review aid. Consult a qualified professional before making decisions.';

function h(value: unknown): string {
  return escapeHtml(value);
}

function loadSorted<T>(dir: string, suffix: string): Array<{ data: T; filename: string }> {
  if (!fs.existsSync(dir)) return [];
  return listRegularFiles(dir, (f) => f.endsWith(suffix))
    .map((f) => {
      try {
        return {
          data: JSON.parse(fs.readFileSync(resolveRegularFileInside(dir, f, 'report file'), 'utf-8')) as T,
          filename: f,
        };
      }
      catch { return null; }
    })
    .filter(Boolean) as Array<{ data: T; filename: string }>;
}

function renderMarkdown(r: CompareReport): string {
  return [
    '# Comparison Report',
    '',
    `> ${DISCLAIMER}`,
    '',
    `**Report ID:** ${r.reportId}  `,
    `**Generated:** ${r.generatedAt}  `,
    `**Source A:** \`${r.sourceA}\`  `,
    `**Source B:** \`${r.sourceB}\``,
    '',
    '## Summary',
    `- Added issues: ${r.addedIssues.length}`,
    `- Removed issues: ${r.removedIssues.length}`,
    `- Changed issues: ${r.changedIssues.length}`,
    `- Payment changes: ${r.paymentChanges.length}`,
    `- Cap table changes: ${r.capTableChanges.length}`,
    `- New warnings: ${r.newWarnings.length}`,
    `- Resolved warnings: ${r.resolvedWarnings.length}`,
    '',
    ...(r.riskScoreChange ? [`**Risk Score Change:** ${r.riskScoreChange}`, ''] : []),
    ...(r.addedIssues.length > 0
      ? ['## Added Issues', ...r.addedIssues.map((i) => `- **[${i.severity}]** ${i.title} (${i.category})`), '']
      : []),
    ...(r.removedIssues.length > 0
      ? ['## Removed Issues', ...r.removedIssues.map((i) => `- [${i.severity}] ${i.title}`), '']
      : []),
    ...(r.changedIssues.length > 0
      ? ['## Changed Issues', ...r.changedIssues.map((c) => `- **${c.title}**: \`${c.field}\` \`${c.from}\` → \`${c.to}\``), '']
      : []),
    ...(r.paymentChanges.length > 0
      ? [
          '## Payment Changes',
          '| Vendor | Amount A | Amount B | Status A | Status B | Change |',
          '|--------|----------|----------|----------|----------|--------|',
          ...r.paymentChanges.map((p) => `| ${p.vendor} | ${p.amountA} | ${p.amountB} | ${p.statusA} | ${p.statusB} | **${p.change}** |`),
          '',
        ]
      : []),
    ...(r.capTableChanges.length > 0
      ? ['## Cap Table Changes', ...r.capTableChanges.map((c) => `- **${c.investor}** (${c.changeType}): ${c.detail}`), '']
      : []),
    ...(r.newWarnings.length > 0
      ? ['## New Warnings', ...r.newWarnings.map((w) => `- ⚠ ${w}`), '']
      : []),
    ...(r.resolvedWarnings.length > 0
      ? ['## Resolved Warnings', ...r.resolvedWarnings.map((w) => `- ✓ ${w}`), '']
      : []),
    '*Generated by Synth v5 — Not legal advice*',
  ].join('\n');
}

export function renderHtml(r: CompareReport): string {
  const stat = (label: string, val: number, color = 'white') =>
    `<div style="background:#1e293b;border:1px solid #334155;border-radius:10px;padding:14px;text-align:center"><div style="font-size:1.4rem;font-weight:bold;color:${color}">${h(val)}</div><div style="font-size:0.72rem;color:#64748b;margin-top:4px">${h(label)}</div></div>`;

  const changeCard = (type: string, color: string, content: string) =>
    `<div style="background:#1e293b;border:1px solid ${color}40;border-radius:8px;padding:10px 14px;margin-bottom:8px;display:flex;align-items:center;gap:10px;flex-wrap:wrap"><span style="font-size:0.72rem;font-weight:600;background:${color}20;color:${color};padding:2px 7px;border-radius:4px">${h(type)}</span>${content}</div>`;

  const payRows = r.paymentChanges.map((p) =>
    `<tr><td>${h(p.vendor)}</td><td>${h(p.amountA)}</td><td>${h(p.amountB)}</td><td>${h(p.statusA)}</td><td>${h(p.statusB)}</td><td style="font-weight:600;color:${p.change === 'added' ? '#ef4444' : p.change === 'removed' ? '#22c55e' : '#eab308'}">${h(p.change)}</td></tr>`
  ).join('');

  const capRows = r.capTableChanges.map((c) =>
    `<tr><td>${h(c.investor)}</td><td style="color:${c.changeType === 'added' ? '#ef4444' : c.changeType === 'removed' ? '#22c55e' : '#eab308'}">${h(c.changeType)}</td><td>${h(c.detail)}</td></tr>`
  ).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Comparison Report — ${h(r.reportId)}</title>
<style>
  body{font-family:system-ui,sans-serif;background:#0f172a;color:#e2e8f0;margin:0;padding:24px}
  .container{max-width:960px;margin:0 auto}
  h1{color:#38bdf8;font-size:1.5rem}
  h2{color:#94a3b8;font-size:1rem;text-transform:uppercase;letter-spacing:.05em;margin-top:28px;margin-bottom:12px}
  .disclaimer{background:#422006;border:1px solid #92400e;border-radius:8px;padding:10px 14px;font-size:0.78rem;color:#fde68a;margin-bottom:20px}
  .stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:20px}
  .sources{background:#1e293b;border:1px solid #334155;border-radius:8px;padding:12px 16px;margin-bottom:16px;font-size:0.82rem}
  table.main{width:100%;border-collapse:collapse;font-size:0.82rem}
  table.main th{background:#0f172a;color:#64748b;padding:6px 10px;text-align:left}
  table.main td{padding:6px 10px;border-bottom:1px solid #1e293b;color:#cbd5e1}
  .section{background:#1e293b;border:1px solid #334155;border-radius:10px;padding:16px;margin-bottom:16px}
  code{background:#0f172a;color:#38bdf8;padding:1px 4px;border-radius:3px;font-size:0.75rem}
  .meta{color:#64748b;font-size:0.78rem}
</style>
</head>
<body>
<div class="container">
  <h1>Comparison Report</h1>
  <p class="meta">${h(r.reportId)} · ${h(r.generatedAt)}</p>
  <div class="disclaimer">⚠ ${DISCLAIMER}</div>
  <div class="sources">
    <strong>A:</strong> <code>${h(r.sourceA)}</code><br>
    <strong>B:</strong> <code>${h(r.sourceB)}</code>
  </div>
  <div class="stats">
    ${stat('Added Issues', r.addedIssues.length, '#ef4444')}
    ${stat('Removed Issues', r.removedIssues.length, '#22c55e')}
    ${stat('Changed Issues', r.changedIssues.length, '#eab308')}
    ${stat('Payment Changes', r.paymentChanges.length, '#38bdf8')}
  </div>

  ${r.addedIssues.length > 0 ? `<h2>Added Issues</h2>${r.addedIssues.map((i) => changeCard('+ Added', '#ef4444', `<strong>${h(i.title)}</strong> <span style="color:#64748b;font-size:0.72rem">${h(i.severity)} · ${h(i.category)}</span>`)).join('')}` : ''}
  ${r.removedIssues.length > 0 ? `<h2>Removed Issues</h2>${r.removedIssues.map((i) => changeCard('- Removed', '#22c55e', `<strong>${h(i.title)}</strong>`)).join('')}` : ''}
  ${r.changedIssues.length > 0 ? `<h2>Changed Issues</h2>${r.changedIssues.map((c) => changeCard('~ Changed', '#eab308', `<strong>${h(c.title)}</strong>: <code>${h(c.field)}</code> <code>${h(c.from)}</code> → <code>${h(c.to)}</code>`)).join('')}` : ''}

  ${r.paymentChanges.length > 0 ? `<h2>Payment Changes</h2><div class="section"><table class="main"><thead><tr><th>Vendor</th><th>Amount A</th><th>Amount B</th><th>Status A</th><th>Status B</th><th>Change</th></tr></thead><tbody>${payRows}</tbody></table></div>` : ''}
  ${r.capTableChanges.length > 0 ? `<h2>Cap Table Changes</h2><div class="section"><table class="main"><thead><tr><th>Investor</th><th>Change</th><th>Detail</th></tr></thead><tbody>${capRows}</tbody></table></div>` : ''}
  ${r.newWarnings.length > 0 ? `<h2>New Warnings</h2><div class="section">${r.newWarnings.map((w) => `<p style="color:#fbbf24;font-size:0.82rem">⚠ ${h(w)}</p>`).join('')}</div>` : ''}
  ${r.resolvedWarnings.length > 0 ? `<h2>Resolved Warnings</h2><div class="section">${r.resolvedWarnings.map((w) => `<p style="color:#22c55e;font-size:0.82rem">✓ ${h(w)}</p>`).join('')}</div>` : ''}
</div>
</body>
</html>`;
}

async function main() {
  console.log('\n╔══════════════════════════════════════════════════╗');
  console.log('║           Synth · Compare                        ║');
  console.log('╚══════════════════════════════════════════════════╝\n');
  console.log('⚠️  Synth is not legal advice or financial advice.\n');

  const args = process.argv.slice(2);
  let roomA: DataRoomSummary;
  let roomB: DataRoomSummary;
  let fileA: string;
  let fileB: string;

  if (args.length >= 2) {
    try {
      roomA = JSON.parse(fs.readFileSync(args[0], 'utf-8'));
      roomB = JSON.parse(fs.readFileSync(args[1], 'utf-8'));
      fileA = path.basename(args[0]);
      fileB = path.basename(args[1]);
    } catch (e) {
      console.error(`  ❌ Could not read files: ${e instanceof Error ? e.message : e}`);
      process.exit(1);
    }
  } else {
    const rooms = loadSorted<DataRoomSummary>(path.join(CWD, 'reports', 'dataroom'), '.json');
    if (rooms.length < 2) {
      console.error('  ❌ Need at least 2 data room reports to compare.');
      console.error('     Run npm run dataroom twice, or pass two JSON paths as arguments.');
      process.exit(1);
    }
    const [rA, rB] = rooms.slice(-2);
    roomA = rA.data;
    roomB = rB.data;
    fileA = rA.filename;
    fileB = rB.filename;
  }

  const logs = loadSorted<IssueLog>(path.join(CWD, 'reports', 'issues'), '.json');
  const logA = logs.length >= 2 ? logs[logs.length - 2].data : logs.length === 1 ? logs[0].data : null;
  const logB = logs.length >= 2 ? logs[logs.length - 1].data : null;

  console.log(`  Comparing:`);
  console.log(`    A: ${fileA}`);
  console.log(`    B: ${fileB}`);
  if (logA && logB) console.log(`  Issue logs: comparing ${logs[logs.length - 2].filename} vs ${logs[logs.length - 1].filename}`);
  console.log('');

  const report = buildCompareReport(fileA, fileB, logA, logB, roomA, roomB);

  fs.mkdirSync(COMPARE_DIR, { recursive: true });
  const ts = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);

  fs.writeFileSync(resolveInside(COMPARE_DIR, `compare-${ts}.json`, 'compare JSON output'), JSON.stringify(report, null, 2));
  fs.writeFileSync(resolveInside(COMPARE_DIR, `compare-${ts}.md`, 'compare markdown output'), renderMarkdown(report));
  fs.writeFileSync(resolveInside(COMPARE_DIR, `compare-${ts}.html`, 'compare HTML output'), renderHtml(report));

  console.log(`  ✅ JSON  → reports/compare/compare-${ts}.json`);
  console.log(`  ✅ MD    → reports/compare/compare-${ts}.md`);
  console.log(`  ✅ HTML  → reports/compare/compare-${ts}.html\n`);
  console.log(`  Added: ${report.addedIssues.length}  Removed: ${report.removedIssues.length}  Changed: ${report.changedIssues.length}`);
  console.log(`  Payment changes: ${report.paymentChanges.length}  Cap table changes: ${report.capTableChanges.length}\n`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
