#!/usr/bin/env tsx
import fs from 'fs';
import path from 'path';
import { chunkText, extractDocumentTitle } from '../lib/parser';
import { runContractReview, runFinancialAnalysis, runMemoGeneration, runRevisionGeneration } from '../lib/ai-provider';
import { renderReviewHTML, renderFinancialHTML, renderMemoHTML, renderRevisionHTML, renderFullPacketHTML } from '../lib/html-renderer';

const CWD = process.cwd();
const INBOX = path.join(CWD, 'documents', 'inbox');
const DEMO_DATA = path.join(CWD, 'src', 'data', 'demo');
const DEMO_ARTIFACTS = path.join(CWD, 'public', 'demo-artifacts');
const SOURCE_FILE = 'sample-saas-agreement.txt';

function ensureDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
}

function copyFile(src: string, dest: string, label: string): void {
  fs.copyFileSync(src, dest);
  console.log(`  ✅ ${label}`);
  console.log(`     → ${dest.replace(CWD + '/', '')}`);
}

function writeFile(dest: string, content: string, label: string): void {
  fs.writeFileSync(dest, content);
  console.log(`  ✅ ${label}`);
  console.log(`     → ${dest.replace(CWD + '/', '')}`);
}

function slug(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60);
}

function buildMarkdown(review: Awaited<ReturnType<typeof runContractReview>>): string {
  const lines: string[] = [
    `# Contract Review: ${review.documentTitle}`,
    '',
    `> **${review.disclaimer}**`,
    '',
    '---',
    '',
    `**Document Type:** ${review.documentType}  `,
    `**Parties:** ${review.parties.join(' · ')}  `,
    `**Risk Score:** ${review.riskScore}/100 — **${review.riskLevel.toUpperCase()}**  `,
    `**Generated:** ${new Date(review.generatedAt).toLocaleDateString()} · ${review.providerMode === 'mock' ? 'Mock Mode' : 'AI Mode'}  `,
    review.sourceFilename ? `**Source File:** ${review.sourceFilename}` : '',
    '',
    '---',
    '',
    '## Executive Summary',
    '',
    review.executiveSummary,
    '',
    '---',
    '',
    '## Risk Matrix',
    '',
    ...review.topRisks.map((r) => [
      `### ${r.severity === 'Critical' ? '🔴' : r.severity === 'High' ? '🟠' : r.severity === 'Medium' ? '🟡' : '🟢'} ${r.severity} — ${r.title}`,
      '',
      r.explanation,
      '',
      r.supportingQuote ? `> "${r.supportingQuote}"` : '',
      '',
      r.location ? `**Location:** ${r.location}  ` : '',
      `**Next step:** ${r.suggestedNextStep}`,
      '',
    ].join('\n')),
    '---',
    '',
    '## Key Terms',
    '',
    `| Term | Value |`,
    `|------|-------|`,
    `| Payment Terms | ${review.paymentTerms} |`,
    `| Renewal | ${review.renewalTerms} |`,
    `| Termination | ${review.terminationTerms} |`,
    `| Governing Law | ${review.governingLaw} |`,
    `| Liability | ${review.liabilityIssues} |`,
    `| Confidentiality | ${review.confidentialityTerms} |`,
    '',
    '## Missing Clauses',
    '',
    ...review.missingClauses.map((c) => `- ${c}`),
    '',
    '## Action Items',
    '',
    ...review.actionItems.map((item, i) => `${i + 1}. ${item}`),
    '',
    '---',
    '',
    '*Generated by Synth v3 · Not legal advice*',
  ];
  return lines.filter((l) => l !== undefined).join('\n');
}

async function main() {
  console.log('\n╔══════════════════════════════════════════════════╗');
  console.log('║         Synth · Seed Demo Artifacts              ║');
  console.log('╚══════════════════════════════════════════════════╝\n');
  console.log('⚠️  Synth is not legal advice or financial advice.');
  console.log('   It is a document review aid. Consult a qualified professional.\n');

  const sourceFile = path.join(INBOX, SOURCE_FILE);
  if (!fs.existsSync(sourceFile)) {
    console.error(`  ❌ Source file not found: ${sourceFile}`);
    console.error(`     Place ${SOURCE_FILE} in documents/inbox/ to run seed-demo.`);
    process.exit(1);
  }

  ensureDir(DEMO_DATA);
  ensureDir(DEMO_ARTIFACTS);

  console.log(`  📄 Processing: ${SOURCE_FILE}\n`);

  const text = chunkText(fs.readFileSync(sourceFile, 'utf-8'));
  const title = extractDocumentTitle(text, SOURCE_FILE);
  const ext = path.extname(SOURCE_FILE);
  const fileSlug = SOURCE_FILE.replace(ext, '');
  const meta = { sourceFilename: SOURCE_FILE, sourceExtension: ext, parsedCharacterCount: text.length };

  process.stdout.write('  → Running review...');
  const review = await runContractReview(text, title, meta);
  console.log(` ✅ Risk: ${review.riskLevel} (${review.riskScore})`);

  process.stdout.write('  → Running financial analysis...');
  const financial = await runFinancialAnalysis(text, title, meta);
  console.log(' ✅');

  process.stdout.write('  → Running memo generation...');
  const memo = await runMemoGeneration(review);
  console.log(' ✅');

  process.stdout.write('  → Running revision generation...');
  const revision = await runRevisionGeneration(text, review);
  console.log(' ✅');

  console.log('\n  Writing demo data files...\n');

  // JSON data → /src/data/demo/
  writeFile(path.join(DEMO_DATA, 'demo-review.json'), JSON.stringify(review, null, 2), 'demo-review.json');
  writeFile(path.join(DEMO_DATA, 'demo-financial.json'), JSON.stringify(financial, null, 2), 'demo-financial.json');
  writeFile(path.join(DEMO_DATA, 'demo-memo.json'), JSON.stringify(memo, null, 2), 'demo-memo.json');
  writeFile(path.join(DEMO_DATA, 'demo-revision.json'), JSON.stringify(revision, null, 2), 'demo-revision.json');

  console.log('');

  // HTML + Markdown → /public/demo-artifacts/
  writeFile(path.join(DEMO_ARTIFACTS, 'demo-review.html'), renderReviewHTML(review), 'demo-review.html');
  writeFile(path.join(DEMO_ARTIFACTS, 'demo-revision.html'), renderRevisionHTML(revision), 'demo-revision.html');
  writeFile(path.join(DEMO_ARTIFACTS, 'demo-memo.html'), renderMemoHTML(memo), 'demo-memo.html');
  writeFile(path.join(DEMO_ARTIFACTS, 'demo-review.md'), buildMarkdown(review), 'demo-review.md');
  writeFile(path.join(DEMO_ARTIFACTS, 'demo-review.json'), JSON.stringify(review, null, 2), 'demo-review.json (public)');

  // Full packet
  const packetHtml = renderFullPacketHTML(review, financial, memo, revision);
  writeFile(path.join(DEMO_ARTIFACTS, 'demo-full-packet.html'), packetHtml, 'demo-full-packet.html');

  // Write manifest
  const manifest = {
    version: '3',
    generatedAt: new Date().toISOString(),
    sourceDocument: SOURCE_FILE,
    description: `Demo fixture data for the Synth /demo route. Generated from ${SOURCE_FILE} in ${review.providerMode} mode.`,
    providerMode: review.providerMode,
    riskScore: review.riskScore,
    riskLevel: review.riskLevel,
    files: {
      review: 'demo-review.json',
      financial: 'demo-financial.json',
      memo: 'demo-memo.json',
      revision: 'demo-revision.json',
    },
    artifacts: {
      fullPacketHtml: '/demo-artifacts/demo-full-packet.html',
      reviewHtml: '/demo-artifacts/demo-review.html',
      revisionHtml: '/demo-artifacts/demo-revision.html',
      memoHtml: '/demo-artifacts/demo-memo.html',
      reviewMarkdown: '/demo-artifacts/demo-review.md',
      reviewJson: '/demo-artifacts/demo-review.json',
    },
  };
  writeFile(path.join(DEMO_DATA, 'demo-manifest.json'), JSON.stringify(manifest, null, 2), 'demo-manifest.json');

  console.log('\n╔══════════════════════════════════════════════════╗');
  console.log('║         ✅ Seed Demo Complete                    ║');
  console.log('╚══════════════════════════════════════════════════╝\n');
  console.log('Demo data updated in:');
  console.log('  src/data/demo/          — JSON fixtures for /demo route');
  console.log('  public/demo-artifacts/  — Downloadable artifacts for /artifacts\n');
  console.log('Next steps:');
  console.log('  npm run dashboard       — Check local dashboard');
  console.log('  npm run build           — Rebuild with updated demo data\n');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
