#!/usr/bin/env tsx
import fs from 'fs';
import path from 'path';
import type { Review } from '../schemas/review.schema';
import type { SpreadsheetAnalysis, DataRoomSummary } from '../schemas/spreadsheet.schema';
import type { IssueLog } from '../schemas/issue.schema';
import { buildIssueLogFromReports } from '../lib/issue-engine';

const CWD = process.cwd();
const ISSUES_DIR = path.join(CWD, 'reports', 'issues');
const EVIDENCE_DIR = path.join(CWD, 'reports', 'evidence');
const DISCLAIMER =
  'Synth is not legal advice or financial advice. It is a document review aid. Consult a qualified professional before making decisions.';

function loadAllJSON<T>(dir: string, suffix: string): Array<{ data: T; filename: string }> {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter((f) => f.endsWith(suffix))
    .sort()
    .map((f) => {
      try { return { data: JSON.parse(fs.readFileSync(path.join(dir, f), 'utf-8')) as T, filename: f }; }
      catch { return null; }
    })
    .filter(Boolean) as Array<{ data: T; filename: string }>;
}

function loadLatestJSON<T>(dir: string, suffix: string): { data: T; filename: string } | null {
  const all = loadAllJSON<T>(dir, suffix);
  return all.length > 0 ? all[all.length - 1] : null;
}

const SEV_ORDER: Record<string, number> = { Critical: 4, High: 3, Medium: 2, Low: 1 };

function sevColor(s: string): string {
  return ({ Critical: '#ef4444', High: '#f97316', Medium: '#eab308', Low: '#22c55e' } as Record<string, string>)[s] ?? '#94a3b8';
}

function statusColor(s: string): string {
  return ({ open: '#f97316', investigating: '#eab308', resolved: '#22c55e', waived: '#64748b' } as Record<string, string>)[s] ?? '#94a3b8';
}

function renderMarkdown(log: IssueLog): string {
  const top10 = [...log.issues].sort((a, b) => (SEV_ORDER[b.severity] ?? 0) - (SEV_ORDER[a.severity] ?? 0)).slice(0, 10);

  return [
    `# ${log.title}`,
    '',
    `> ${DISCLAIMER}`,
    '',
    `**Generated:** ${log.generatedAt}  `,
    `**Log ID:** ${log.logId}  `,
    `**Total Issues:** ${log.totalIssues} (Critical: ${log.criticalCount}, High: ${log.highCount}, Open: ${log.openCount})`,
    '',
    '---',
    '',
    '## Top 10 Issues to Resolve',
    '',
    ...top10.flatMap((issue, i) => [
      `### ${i + 1}. [${issue.severity}] ${issue.title}`,
      '',
      `**Category:** ${issue.category} | **Status:** ${issue.status} | **Sources:** ${issue.sourceFiles.join(', ')}`,
      '',
      issue.evidenceQuotes.length > 0
        ? `> "${issue.evidenceQuotes[0]}"`
        : '_No direct quote — see evidence ledger._',
      '',
      `**Recommendation:** ${issue.recommendation}`,
      '',
    ]),
    '---',
    '',
    '## All Issues',
    '',
    '| # | Title | Severity | Category | Status | Sources |',
    '|---|-------|----------|----------|--------|---------|',
    ...log.issues.map((i, idx) =>
      `| ${idx + 1} | ${i.title} | ${i.severity} | ${i.category} | ${i.status} | ${i.sourceFiles.join('; ')} |`
    ),
    '',
    '---',
    '',
    '## Evidence Ledger',
    '',
    ...log.evidence.flatMap((e) => [
      `### ${e.evidenceId}`,
      `**Issue:** ${e.issueId} | **Source:** ${e.sourceFilename}${e.sheetName ? ` (${e.sheetName})` : ''} | **Verified:** ${e.isVerified ? 'Yes' : 'No'}${e.verificationNote ? ` — ${e.verificationNote}` : ''}`,
      e.documentQuote ? `> "${e.documentQuote}"` : '',
      e.spreadsheetRow ? `Row: \`${e.spreadsheetRow}\`` : '',
      '',
    ].filter((l) => l !== '')),
    '',
    '*Generated by Synth v5 — Not legal advice*',
  ].join('\n');
}

function renderHtml(log: IssueLog): string {
  const top10 = [...log.issues].sort((a, b) => (SEV_ORDER[b.severity] ?? 0) - (SEV_ORDER[a.severity] ?? 0)).slice(0, 10);

  const badge = (s: string, color: string) =>
    `<span style="border:1px solid ${color}40;color:${color};font-size:0.72rem;padding:2px 7px;border-radius:12px;font-weight:600">${s}</span>`;

  const top10Cards = top10.map((issue, i) => `
    <div style="background:#1e293b;border:1px solid #334155;border-radius:10px;padding:14px;margin-bottom:12px">
      <div style="display:flex;align-items:flex-start;gap:10px;margin-bottom:8px;flex-wrap:wrap">
        <span style="background:#0f172a;color:#64748b;min-width:24px;height:24px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:0.72rem;font-weight:bold">${i + 1}</span>
        <strong style="color:#e2e8f0;font-size:0.88rem;flex:1">${issue.title}</strong>
        ${badge(issue.severity, sevColor(issue.severity))}
        <span style="color:${statusColor(issue.status)};font-size:0.72rem;background:#0f172a;padding:2px 7px;border-radius:4px">${issue.status}</span>
      </div>
      <div style="font-size:0.78rem;color:#64748b;margin-bottom:8px">Category: <strong style="color:#94a3b8">${issue.category}</strong> · Sources: <code style="background:#0f172a;color:#38bdf8;padding:1px 4px;border-radius:3px;font-size:0.72rem">${issue.sourceFiles.join(', ')}</code></div>
      ${issue.evidenceQuotes.length > 0
        ? `<blockquote style="border-left:3px solid #1d4ed8;padding-left:10px;color:#93c5fd;font-style:italic;font-size:0.8rem;margin:8px 0">"${issue.evidenceQuotes[0]}"</blockquote>`
        : '<p style="color:#475569;font-size:0.78rem;font-style:italic">No direct quote — see evidence ledger.</p>'}
      <p style="color:#38bdf8;font-size:0.82rem;margin-top:8px">→ ${issue.recommendation}</p>
    </div>`).join('');

  const allRows = log.issues.map((issue, i) => `
    <tr>
      <td style="color:#64748b">${i + 1}</td>
      <td style="color:#e2e8f0">${issue.title}</td>
      <td>${badge(issue.severity, sevColor(issue.severity))}</td>
      <td style="color:#94a3b8">${issue.category}</td>
      <td style="color:${statusColor(issue.status)}">${issue.status}</td>
      <td><code style="background:#0f172a;color:#38bdf8;padding:1px 4px;border-radius:3px;font-size:0.75rem">${issue.sourceFiles.join('; ')}</code></td>
    </tr>`).join('');

  const evRows = log.evidence.map((e) => `
    <tr>
      <td><code style="background:#0f172a;color:#38bdf8;padding:1px 4px;border-radius:3px;font-size:0.72rem">${e.evidenceId}</code></td>
      <td><code style="background:#0f172a;color:#94a3b8;padding:1px 4px;border-radius:3px;font-size:0.72rem">${e.issueId}</code></td>
      <td style="color:#94a3b8"><code style="font-size:0.72rem">${e.sourceFilename}</code></td>
      <td style="color:${e.isVerified ? '#22c55e' : '#f97316'};font-size:0.78rem">${e.isVerified ? '✓ Verified' : 'Unverified'}</td>
      <td style="color:#cbd5e1;font-size:0.78rem;font-style:italic">${e.documentQuote ? `"${e.documentQuote.slice(0, 80)}${e.documentQuote.length > 80 ? '…' : ''}"` : e.spreadsheetRow ? `<code style="font-style:normal">${e.spreadsheetRow}</code>` : '—'}</td>
    </tr>`).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Issue Log — ${log.title}</title>
<style>
  body{font-family:system-ui,sans-serif;background:#0f172a;color:#e2e8f0;margin:0;padding:24px}
  .container{max-width:960px;margin:0 auto}
  h1{color:#38bdf8;font-size:1.5rem}
  h2{color:#94a3b8;font-size:1rem;text-transform:uppercase;letter-spacing:.05em;margin-top:28px;margin-bottom:12px}
  .disclaimer{background:#422006;border:1px solid #92400e;border-radius:8px;padding:10px 14px;font-size:0.78rem;color:#fde68a;margin-bottom:20px}
  .stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:20px}
  .stat{background:#1e293b;border:1px solid #334155;border-radius:10px;padding:14px;text-align:center}
  .stat-val{font-size:1.6rem;font-weight:bold;color:white}
  .stat-lbl{font-size:0.72rem;color:#64748b;margin-top:4px}
  table.main{width:100%;border-collapse:collapse;font-size:0.82rem}
  table.main th{background:#0f172a;color:#64748b;padding:6px 10px;text-align:left}
  table.main td{padding:6px 10px;border-bottom:1px solid #1e293b;color:#cbd5e1;vertical-align:top}
  .section{background:#1e293b;border:1px solid #334155;border-radius:10px;padding:16px;margin-bottom:16px}
  .meta{color:#64748b;font-size:0.78rem}
</style>
</head>
<body>
<div class="container">
  <h1>${log.title}</h1>
  <p class="meta">Generated: ${log.generatedAt} · Log ID: ${log.logId}</p>
  <div class="disclaimer">⚠ ${DISCLAIMER}</div>
  <div class="stats">
    <div class="stat"><div class="stat-val">${log.totalIssues}</div><div class="stat-lbl">Total Issues</div></div>
    <div class="stat"><div class="stat-val" style="color:#ef4444">${log.criticalCount}</div><div class="stat-lbl">Critical</div></div>
    <div class="stat"><div class="stat-val" style="color:#f97316">${log.highCount}</div><div class="stat-lbl">High</div></div>
    <div class="stat"><div class="stat-val" style="color:#eab308">${log.openCount}</div><div class="stat-lbl">Open</div></div>
  </div>
  <h2>Top 10 Issues to Resolve</h2>
  ${top10Cards}
  <h2>All Issues</h2>
  <div class="section">
    <table class="main">
      <thead><tr><th>#</th><th>Title</th><th>Severity</th><th>Category</th><th>Status</th><th>Sources</th></tr></thead>
      <tbody>${allRows}</tbody>
    </table>
  </div>
  <h2>Evidence Ledger</h2>
  <div class="section">
    <table class="main">
      <thead><tr><th>Evidence ID</th><th>Issue ID</th><th>Source</th><th>Verified</th><th>Quote / Row</th></tr></thead>
      <tbody>${evRows}</tbody>
    </table>
  </div>
</div>
</body>
</html>`;
}

async function main() {
  console.log('\n╔══════════════════════════════════════════════════╗');
  console.log('║           Synth · Triage                         ║');
  console.log('╚══════════════════════════════════════════════════╝\n');
  console.log('⚠️  Synth is not legal advice or financial advice.\n');

  const reviewFiles = loadAllJSON<Review>(path.join(CWD, 'reports', 'reviews'), '-review.json');
  const spreadsheetFiles = loadAllJSON<SpreadsheetAnalysis>(path.join(CWD, 'reports', 'tables'), '-spreadsheet.json');
  const dataroomResult = loadLatestJSON<DataRoomSummary>(path.join(CWD, 'reports', 'dataroom'), '.json');

  const reviews = reviewFiles.map((r) => r.data);
  const spreadsheets = spreadsheetFiles.map((s) => s.data);
  const datarooms = dataroomResult ? [dataroomResult.data] : [];

  console.log(`  Reviews loaded:     ${reviews.length}`);
  console.log(`  Spreadsheets:       ${spreadsheets.length}`);
  console.log(`  Data room reports:  ${datarooms.length}\n`);

  if (reviews.length === 0 && datarooms.length === 0) {
    console.error('  ❌ No reports found.');
    console.error('     Run: npm run demo   (contracts)');
    console.error('     Run: npm run dataroom   (data room)');
    process.exit(1);
  }

  const sourceReportNames = [
    ...reviewFiles.map((r) => `reviews/${r.filename}`),
    ...spreadsheetFiles.map((s) => `tables/${s.filename}`),
    ...(dataroomResult ? [`dataroom/${dataroomResult.filename}`] : []),
  ];

  console.log('  Building issue log...');
  const log = buildIssueLogFromReports(reviews, spreadsheets, datarooms, sourceReportNames);

  fs.mkdirSync(ISSUES_DIR, { recursive: true });
  fs.mkdirSync(EVIDENCE_DIR, { recursive: true });

  const ts = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);

  const jsonPath = path.join(ISSUES_DIR, `issue-log-${ts}.json`);
  const mdPath = path.join(ISSUES_DIR, `issue-log-${ts}.md`);
  const htmlPath = path.join(ISSUES_DIR, `issue-log-${ts}.html`);
  const evPath = path.join(EVIDENCE_DIR, `evidence-${ts}.json`);

  fs.writeFileSync(jsonPath, JSON.stringify(log, null, 2));
  fs.writeFileSync(mdPath, renderMarkdown(log));
  fs.writeFileSync(htmlPath, renderHtml(log));
  fs.writeFileSync(evPath, JSON.stringify({ generatedAt: new Date().toISOString(), issueLogId: log.logId, evidence: log.evidence }, null, 2));

  console.log(`\n  ✅ Issue Log JSON  → reports/issues/issue-log-${ts}.json`);
  console.log(`  ✅ Issue Log MD    → reports/issues/issue-log-${ts}.md`);
  console.log(`  ✅ Issue Log HTML  → reports/issues/issue-log-${ts}.html`);
  console.log(`  ✅ Evidence JSON   → reports/evidence/evidence-${ts}.json\n`);
  console.log(`  Total issues: ${log.totalIssues}`);
  console.log(`  Critical: ${log.criticalCount}  High: ${log.highCount}  Open: ${log.openCount}\n`);
  console.log('  Next steps:');
  console.log('    npm run export   → CSV + XLSX exports');
  console.log('    npm run compare  → compare two runs\n');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
